# This is run as a precondition to commits, run manually via `pre-commit run`

# When adding new hooks, it may make sense to once run
# `pre-commit run --all-files` as by default only changed files are checked

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
    description: Check yaml files for parseable syntax
  - id: check-added-large-files
    description: Prevent large files from being committed
  - id: check-merge-conflict
    description: Check for files that contain merge conflict strings
  - id: check-symlinks
    description: Check for symlinks which do not point to anything
  - id: trailing-whitespace
    description: Trim trailing whitespaces
  - id: end-of-file-fixer
    description: Fix empty lines at ends of files
  - id: detect-private-key
    description: Detects the presence of private keys
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.9
  hooks:
    # Run the linter.
    - id: ruff
      args:
        - --fix
        - --config
        - pyproject.toml

    # Run the formatter.
    - id: ruff-format
      args:
        - --config
        - pyproject.toml
